version: "3.8"  # Use Docker Compose file format version 3.8

services:
  frontend:
    container_name: familytree-frontend  # Name of the Nginx container
    image: nginx:alpine                  # Use a lightweight Nginx image
    ports:
      - "80:80"                          # Map container's port 80 to host port 80
    volumes:
      - ./familyTreeUI/dist:/usr/share/nginx/html  # Serve built React files from this directory
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config (read-only)
    depends_on:
      - backend                          # Wait for backend to start before this container starts

  backend:
    container_name: familytree-backend   # Name of the Spring Boot container
    build:
      context: ./familytree                 # Docker build context is the backend folder
      dockerfile: Dockerfile            # Dockerfile used for backend
    ports:
      - "8080:8080"                      # Map container's port 8080 to host port 8080
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687  # URI of the Neo4j service
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j  # Username for Neo4j auth
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=gameofthrones  # Password for Neo4j auth
    depends_on:
      - neo4j                            # Ensure Neo4j is up before backend

  neo4j:
    container_name: familytree-neo4j     # Name of the Neo4j database container
    image: neo4j                         # Use Neo4j version 5.15 image
    ports:
      - "7474:7474"                      # Neo4j browser web interface
      - "7687:7687"                      # Neo4j Bolt protocol for database access
    environment:
      - NEO4J_AUTH=neo4j/gameofthrones   # Sets up Neo4j with username/password
    volumes:
      - neo4j-data:/data                 # Persist database data

volumes:
  neo4j-data:                            # Named volume to persist Neo4j data
