version: "3.8"  # Use Docker Compose file format version 3.8

services:
  frontend:
    container_name: familytree-frontend  # Name of the Nginx container
    image: nginx:alpine                  # Use a lightweight Nginx image
    ports:
      - "${FRONTEND_PORT}:80"           # Map container's port 80 to host port 3000
    volumes:
      - ./familyTreeUI/dist:/usr/share/nginx/html  # Serve built React files from this directory
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config (read-only)
    networks:
      - backendnet
    depends_on:
      - backend                          # Wait for backend to start before this container starts

  backend:
    container_name: familytree-backend   # Name of the Spring Boot container
    build:
      context: ./familytree                 # Docker build context is the backend folder
      dockerfile: Dockerfile            # Dockerfile used for backend
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - .env                     # Map container's port 8080 to host port 8080
    networks:
      - backendnet
    environment:
      NEO4J_URI: ${NEO4J_URI}            # URI of the Neo4j service
      NEO4J_USERNAME: ${NEO4J_USERNAME}  # Username for Neo4j auth
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}  # Password for Neo4j auth
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PORT: ${SPRING_PORT}
      SPRING_REDIS_HOST: familytree-redis
      SPRING_REDIS_PORT: 6379
      SPRING_SESSION_TIMEOUT: ${REDIS_SESSION_TTL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on:
      - neo4j  # Wait for Neo4j before starting
      - redis  # Wait for Redis before starting
      - rabbitmq # Wait for RabbitMQ before starting

  rabbitmq:
    container_name: familytree-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    networks:
      - backendnet

  neo4j:
    container_name: familytree-neo4j     # Name of the Neo4j database container
    image: neo4j                         # Use Neo4j version 5.15 image
    ports:
      - "7474:7474"                      # Neo4j browser web interface
      - "7687:7687"                      # Neo4j Bolt protocol for database access
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"   # Sets up Neo4j with username/password
    volumes:
      - neo4j-data:/data                 # Persist database data
    networks:
      - backendnet
      
  redis:
    container_name: familytree-redis                # Redis cache for sessions
    image: redis:7.2-alpine                # Lightweight Redis image
    ports:
      - "6379:6379"                      # Redis port
    volumes:
      - redis-data:/data
    networks:
      - backendnet

  chatbot:
    container_name: familytree-chatbot
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backendnet
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: ${NEO4J_DATABASE}
      GROQ_KEY: ${GROQ_KEY}
    depends_on:
      - neo4j

volumes:
  neo4j-data:  # Volume for Neo4j data
  redis-data:  # Volume for Redis data
  rabbitmq-data: # Volume for RabbitMQ data

networks:
  backendnet:
    driver: bridge

command:
  down:
    options: "-rmi all"